version: '2.4'

services:
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 15s
      timeout: 10s
      retries: 3

  api:
    image: somprasongd/jasperreports-generater:latest
    restart: always
    ports:
      - "9090:8080"
    environment:
#      - JAVA_OPTS=-Dredis.host=redis
      - SPRING_REDIS_HOST=redis
    volumes:
      - ./jaspers:/app/jaspers
    healthcheck:
      test: curl -f http://127.0.0.1:8080/api/healthz
    depends_on:
      redis:
        condition: service_healthy